### ISSUE TITLE
lru_cache in decorator section, context manager in functionnal programming

### ISSUE THREAD

**Issue by 0pb** [dimi-fn/Various-Data-Science-Scripts#2]
Hello,

I suggest adding an **@lru_cache** short description in the decorator section of the [functional programming part](https://github.com/dimi-fn/Various-Data-Science-Scripts/tree/main/Functional_Programming) as well as a context manager part.

The lru_cache is a great example of what a decorator can do (caching data to dramatically reduce computation). 
Caching is a great concept to learn and master, which seems to fit in your project.
You also already use the functools module for the "reduce" part, so It won't be weird to introduce the lru_cache. 
ref : https://docs.python.org/3/library/functools.html
https://realpython.com/lru-cache-python/

The context manager "**with**" is a common tool found in python code, and it should be useful to explain how to make your own.
ref : https://www.youtube.com/watch?v=cKPlPJyQrt4 (talk that tie together decorator, generator nicely).

On a side note, I also suggest reducing the range (line `for num in (range(0, 10000)):`) in [27](https://github.com/dimi-fn/Various-Data-Science-Scripts/blob/main/Functional_Programming/Functional_Programming.ipynb), counting to 10 000 or 1000 wouldn't change the example in itself, but it would reduce the amount of space wasted in the page.

**Comment by dimi-fn** [comment]
Hi @0pb! Thanks for reaching out!

Please, feel free to contribute to the functional programming part with a pull request, I will be glad to review it, and thanks for the ideas. Regarding the output, if you open the colab notebook where I was working for that part (there's a link provided in the directory) you will notice that the output is rendered horizontally and not vertically. I wanted to use a large number, hence the 10,000, in order to show the use of a decorator there.
